In [1]:
import pandas as pd
import glob
import codecs
from pandas import Series, DataFrame

In [2]:
glob.glob('*.csv')

['Stress.csv',
 'Support.csv',
 '圧力_温度_配管ID.csv',
 '節点.csv',
 '配管特性.csv',
 'ｻﾎﾟｰﾄ.csv']

In [54]:
data1 = pd.read_csv("Stress.csv",encoding='shift_jis')
data1

,Internal1,Internal2,PointOrder,CombinationOrder,PlusSideOrder,PercSoilOrder,CategoryOrder,Segment,Point,Combination,...,TorsionalMoment,AxialForce,InPlaneSIF,OutPlaneSIF,Equation,SectMod1,ResultantMoment,B1,B2,StressEquation
0,65542,65531,1894,1,1,0,1,A,A03 N-,GR + Max P{1},...,0.00,0.0,1.00,0.0,15,0.0,291.35,0.0,0.0,NaN
1,131078,65531,1894,2,1,0,2,A,A03 N-,TR:Amb to T1{1},...,532.83,0.0,1.00,0.0,17,0.0,0.00,0.0,0.0,NaN
2,196614,65531,1894,3,1,0,2,A,A03 N-,Amb to T1{1},...,532.83,0.0,1.00,0.0,17,0.0,0.00,0.0,0.0,NaN
3,65542,5,1895,1,2,0,1,A,A03 N+,GR + Max P{1},...,0.00,0.0,2.84,0.0,15,0.0,291.35,0.0,0.0,NaN
4,131078,5,1895,2,2,0,2,A,A03 N+,TR:Amb to T1{1},...,532.83,0.0,2.84,0.0,17,0.0,0.00,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1147,131446,65531,2270,2,1,0,2,Q,Q06 F,TR:Amb to T1{1},...,121.13,0.0,1.00,0.0,17,0.0,0.00,0.0,0.0,NaN
1148,196982,65531,2270,3,1,0,2,Q,Q06 F,Amb to T1{1},...,121.13,0.0,1.00,0.0,17,0.0,0.00,0.0,0.0,NaN
1149,65911,65531,2271,1,1,0,1,Q,Q07,GR + Max P{1},...,0.00,0.0,1.00,0.0,15,0.0,22.12,0.0,0.0,NaN
1150,131447,65531,2271,2,1,0,2,Q,Q07,TR:Amb to T1{1},...,117.28,0.0,1.00,0.0,17,0.0,0.00,0.0,0.0,NaN
1151,196983,65531,2271,3,1,0,2,Q,Q07,Amb to T1{1},...,117.28,0.0,1.00,0.0,17,0.0,0.00,0.0,0.0,NaN

In [55]:
data1 = data1[data1["Category"] == "Sustain"]

In [56]:
for col_name in data1.columns:
    if col_name != "Point" and col_name != "Category" and col_name != "Stress" and col_name != "Ratio":
        data1 = data1.drop(col_name,axis=1)

In [57]:
data1

       Point Category  Stress  Ratio
0     A03 N-  Sustain    3.81   0.06
3     A03 N+  Sustain    7.18   0.11
6     A03 F-  Sustain    2.47   0.03
9     A03 F+  Sustain    1.60   0.02
12       A04  Sustain   14.14   0.22
...      ...      ...     ...    ...
1137   Q05 N  Sustain    2.94   0.03
1140   Q05 F  Sustain    2.46   0.02
1143   Q06 N  Sustain    3.20   0.03
1146   Q06 F  Sustain    3.11   0.03
1149     Q07  Sustain    2.79   0.03

[384 rows x 4 columns]

In [58]:
data2 = pd.read_csv("Support.csv",encoding='shift_jis')

In [59]:
for col_name in data2.columns:
    if col_name != "Point" and col_name != "Type" :
        data2 = data2.drop(col_name,axis=1)
        
data2

    Point      Type
0     A02     Guide
1     A02     Guide
2     A02     Guide
3     A04  V - Stop
4     A04  V - Stop
..    ...       ...
133   P02  V - Stop
134   P02  V - Stop
135   Q02  V - Stop
136   Q02  V - Stop
137   Q02  V - Stop

[138 rows x 2 columns]

In [60]:
data2 = data2.drop_duplicates()
data2

    Point      Type
0     A02     Guide
3     A04  V - Stop
6     A06  V - Stop
9     A11     Guide
12    A13     Guide
15    A14     Guide
18    A15     Guide
21    A18     Guide
24    A20     Guide
27    A25     Guide
30    A28     Guide
33    A33     Guide
36    B02     Guide
39    B07     Guide
42    B09     Guide
45    D04     Guide
48    D04  V - Stop
51    E05     Guide
54    E05  V - Stop
57    F01     Guide
60    F06     Guide
63    F11     Guide
66    F13     Guide
69    G01     Guide
72    G04     Guide
75    G04  V - Stop
78    G06     Guide
81    G08     Guide
84    I02  V - Stop
87    I03     Guide
90    J01  V - Stop
93    J02  V - Stop
96    J07     Guide
99    J07  V - Stop
102   K02     Guide
105   K05     Guide
108   K07  V - Stop
111   K12     Guide
114   K13     Guide
117   K15     Guide
120   L01     Guide
123   L01  V - Stop
126   N03     Guide
129   N07     Guide
132   P02  V - Stop
135   Q02  V - Stop

In [65]:
data_stress_type = pd.merge(data1,data2,how = "outer",left_on = 'Point',right_on='Point')
data_stress_type

      Point Category  Stress  Ratio      Type
0    A03 N-  Sustain    3.81   0.06       NaN
1    A03 N+  Sustain    7.18   0.11       NaN
2    A03 F-  Sustain    2.47   0.03       NaN
3    A03 F+  Sustain    1.60   0.02       NaN
4       A04  Sustain   14.14   0.22  V - Stop
..      ...      ...     ...    ...       ...
384   Q05 N  Sustain    2.94   0.03       NaN
385   Q05 F  Sustain    2.46   0.02       NaN
386   Q06 N  Sustain    3.20   0.03       NaN
387   Q06 F  Sustain    3.11   0.03       NaN
388     Q07  Sustain    2.79   0.03       NaN

[389 rows x 5 columns]

In [66]:
data_series = Series(data_stress_type['Type'])
pd.Series.value_counts(data_series)

Guide       33
V - Stop    13
Name: Type, dtype: int64

In [67]:
data_stress_type.at[data_stress_type['Type'] == "Guide",'Type'] = 1
data_stress_type.at[data_stress_type['Type'] == "V - Stop",'Type'] = 2
data_test = data_stress_type.fillna(0)
data_series = Series(data_test['Type'])
pd.Series.value_counts(data_series)

0    343
1     33
2     13
Name: Type, dtype: int64

In [68]:
data_test.corr()

          Stress     Ratio      Type
Stress  1.000000  0.961582  0.171173
Ratio   0.961582  1.000000  0.143654
Type    0.171173  0.143654  1.000000

In [69]:
#データの分類
from sklearn.model_selection import train_test_split
#決定木
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

#説明変数と目的変数
X = data_test.drop(['Point','Category','Type'],axis=1)
Y = data_test['Type']

In [70]:
#データを分ける
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,random_state = 50)

#決定木インスタンス（エントロピー、深さ5）
tree_model = DecisionTreeClassifier(criterion='entropy',max_depth=5,random_state=50)

In [71]:
#fitting
tree_model.fit(X_train,Y_train)

print("train:",tree_model.__class__.__name__,tree_model.score(X_train,Y_train))
print("test:",tree_model.__class__.__name__ , tree_model.score(X_test,Y_test))

train: DecisionTreeClassifier 0.9072164948453608
test: DecisionTreeClassifier 0.8571428571428571

In [73]:
data3 = pd.read_csv("圧力_温度_配管ID.csv", encoding='shift_jis')
data4 = pd.read_csv('配管特性.csv',encoding='shift_jis')
data3_frame = DataFrame(data3)
data4_frame = DataFrame(data4)
data34 = pd.merge(data3_frame,data4_frame,how='left',left_on='配管 ID',right_on = '配管ID')
data34 = data34.drop("To",axis=1)
for col_name in data34.columns:
    print(col_name,data34[col_name].dtype)
data34_dummy = pd.get_dummies(data34[data34.columns[data34.columns != 'From']])
data34_dummy['From'] = data34['From']
data_press_type = pd.merge(data34_dummy,data2,how = "outer",left_on = 'From',right_on='Point')
data_press_type

From object
材質 object
配管 ID object
呼び径 (mm)_x int64
ｹｰｽ 1 圧力 (N/mm2) float64
ｹｰｽ 1 温度 (deg C) int64
ｹｰｽ 1 自動_1 int64
ｹｰｽ 1 線膨張量 (mm/m) float64
ｹｰｽ 1 自動_2 int64
ｹｰｽ 1 運転時弾性係数 (E6 N/mm2) float64
ｹｰｽ 1 自動_3 int64
ｹｰｽ 1 運転時許容応力 (N/mm2) int64
配管ID object
ﾀｸﾞ ﾅﾝﾊﾞｰ object
呼び径 (mm)_y int64
実外径 (mm) float64
ｽｹｼﾞｭｰﾙ object
肉厚 (mm) float64
腐れ代 (mm) int64
製作公差 (mm) float64
保温厚さ (mm) int64
保温材質 object
保温材密度 (kg/m3) object
外装板厚 (mm) int64
外装板材質 object
外装板密度 (kg/m3) object
ﾗｲﾆﾝｸﾞ厚さ (mm) int64
ﾗｲﾆﾝｸﾞ密度 (kg/m3) object
ﾗｲﾝ ｸﾗｽ object
流体比重 float64
配管材質 object
最低温度の警告 int64
溶接E係数 int64
溶接W係数 自動 object
溶接W係数 object
応力振幅 低減係数 int64
常温時許容応力 (N/mm2) float64
最小降伏点(Sy) (N/mm2) int64
引張強さ(Su) (N/mm2) int64
縦弾性係数 (E6 N/mm2) float64
周方向弾性係数 (E6 N/mm2) float64
せん断弾性係数 (E6 N/mm2) float64
密度 (kg/m3) int64
ﾎﾟｱｿﾝ比 float64

,呼び径 (mm)_x,ｹｰｽ 1 圧力 (N/mm2),ｹｰｽ 1 温度 (deg C),ｹｰｽ 1 自動_1,ｹｰｽ 1 線膨張量 (mm/m),ｹｰｽ 1 自動_2,ｹｰｽ 1 運転時弾性係数 (E6 N/mm2),ｹｰｽ 1 自動_3,ｹｰｽ 1 運転時許容応力 (N/mm2),呼び径 (mm)_y,...,ﾗｲﾝ ｸﾗｽ_,配管材質_SGP-B,配管材質_SGP-E,配管材質_STPG370-S,配管材質_STPT370-S,溶接W係数 自動_,溶接W係数_,From,Point,Type
0,150,0.1,100,1,0.91,1,0.19,1,62,150,...,1,0,1,0,0,1,1,A00,NaN,NaN
1,150,0.1,100,1,0.91,1,0.19,1,62,150,...,1,0,1,0,0,1,1,A01 N,NaN,NaN
2,150,0.1,100,1,0.91,1,0.19,1,62,150,...,1,0,1,0,0,1,1,A01 F,NaN,NaN
3,150,0.1,100,1,0.91,1,0.19,1,62,150,...,1,0,1,0,0,1,1,A02,A02,Guide
4,150,0.1,100,1,0.91,1,0.19,1,62,150,...,1,0,1,0,0,1,1,A03 N,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,50,0.1,100,1,0.91,1,0.19,1,106,50,...,1,0,0,0,1,1,1,Q05 N,NaN,NaN
261,50,0.1,100,1,0.91,1,0.19,1,106,50,...,1,0,0,0,1,1,1,Q05 F,NaN,NaN
262,50,0.1,100,1,0.91,1,0.19,1,106,50,...,1,0,0,0,1,1,1,Q06 N,NaN,NaN
263,50,0.1,100,1,0.91,1,0.19,1,106,50,...,1,0,0,0,1,1,1,Q06 F,NaN,NaN
264,50,0.1,100,1,0.91,1,0.19,1,106,50,...,1,0,0,0,1,1,1,Q07,NaN,NaN

In [74]:
data_series = Series(data_press_type['Type'])
pd.Series.value_counts(data_series)

Guide       33
V - Stop    13
Name: Type, dtype: int64

In [75]:
data_press_type.at[data_press_type['Type'] == "Guide",'Type'] = 1
data_press_type.at[data_press_type['Type'] == "V - Stop",'Type'] = 2
data_test_press = data_press_type.fillna(0)
data_series = Series(data_test_press['Type'])
pd.Series.value_counts(data_series)

0    219
1     33
2     13
Name: Type, dtype: int64

In [76]:
data_test_press

,呼び径 (mm)_x,ｹｰｽ 1 圧力 (N/mm2),ｹｰｽ 1 温度 (deg C),ｹｰｽ 1 自動_1,ｹｰｽ 1 線膨張量 (mm/m),ｹｰｽ 1 自動_2,ｹｰｽ 1 運転時弾性係数 (E6 N/mm2),ｹｰｽ 1 自動_3,ｹｰｽ 1 運転時許容応力 (N/mm2),呼び径 (mm)_y,...,ﾗｲﾝ ｸﾗｽ_,配管材質_SGP-B,配管材質_SGP-E,配管材質_STPG370-S,配管材質_STPT370-S,溶接W係数 自動_,溶接W係数_,From,Point,Type
0,150,0.1,100,1,0.91,1,0.19,1,62,150,...,1,0,1,0,0,1,1,A00,0,0
1,150,0.1,100,1,0.91,1,0.19,1,62,150,...,1,0,1,0,0,1,1,A01 N,0,0
2,150,0.1,100,1,0.91,1,0.19,1,62,150,...,1,0,1,0,0,1,1,A01 F,0,0
3,150,0.1,100,1,0.91,1,0.19,1,62,150,...,1,0,1,0,0,1,1,A02,A02,1
4,150,0.1,100,1,0.91,1,0.19,1,62,150,...,1,0,1,0,0,1,1,A03 N,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,50,0.1,100,1,0.91,1,0.19,1,106,50,...,1,0,0,0,1,1,1,Q05 N,0,0
261,50,0.1,100,1,0.91,1,0.19,1,106,50,...,1,0,0,0,1,1,1,Q05 F,0,0
262,50,0.1,100,1,0.91,1,0.19,1,106,50,...,1,0,0,0,1,1,1,Q06 N,0,0
263,50,0.1,100,1,0.91,1,0.19,1,106,50,...,1,0,0,0,1,1,1,Q06 F,0,0
264,50,0.1,100,1,0.91,1,0.19,1,106,50,...,1,0,0,0,1,1,1,Q07,0,0

In [77]:
#データの分類
from sklearn.model_selection import train_test_split
#決定木
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

#説明変数と目的変数
X = data_test_press.drop(['From','Point','Type'],axis=1)
Y = data_test_press['Type']

In [78]:
#データを分ける
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,random_state = 50)

#決定木インスタンス（エントロピー、深さ5）
tree_model = DecisionTreeClassifier(criterion='entropy',max_depth=5,random_state=50)

In [79]:
#fitting
tree_model.fit(X_train,Y_train)

print("train:",tree_model.__class__.__name__,tree_model.score(X_train,Y_train))
print("test:",tree_model.__class__.__name__ , tree_model.score(X_test,Y_test))

train: DecisionTreeClassifier 0.8434343434343434
test: DecisionTreeClassifier 0.7761194029850746